#!/bin/bash

case $1 in
  "start")
    i3-gnome-pomodoro start
    /home/francis/Scripts/hosts-manager study
    ;;
  "stop")
    i3-gnome-pomodoro stop
    /home/francis/Scripts/hosts-manager normal
    ;;
  "pause")
    i3-gnome-pomodoro pause
    /home/francis/Scripts/hosts-manager normal
    ;;
  "resume")
    i3-gnome-pomodoro resume
    /home/francis/Scripts/hosts-manager study
    ;;
esac
